# Generated by Django 5.2 on 2025-05-01 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1)),
                ('idade', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('data_inscricao', models.DateField(auto_now_add=True)),
                ('plano', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia', models.IntegerField(help_text='Dias de treino por semana')),
                ('estacao', models.CharField(choices=[('Verão', 'Verão'), ('Outono', 'Outono'), ('Inverno', 'Inverno'), ('Primavera', 'Primavera')], max_length=10)),
                ('objetivo_alcancado', models.BooleanField()),
                ('satisfacao', models.IntegerField(help_text='Nota de 0 a 10')),
                ('lesoes', models.BooleanField()),
                ('chance_desistencia', models.FloatField(blank=True, null=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientesmodel')),
            ],
        ),
    ]
